version: "3.9"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresel/data
  #   environment:
  #     POSTGRES_PASSWORD: oom:D@~^AHo2xl`fe6d&
  web-api:
    build: web-api/
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - ./web-api:/myapp
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
