// TODOS
export const TODO_CREATE = 'TODO_CREATE';
export const TODOS_LOAD_SUCCESS = 'TODOS_LOAD_SUCCESS';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_DELETE_OPTIMISTIC = 'TODO_DELETE_OPTIMISTIC';

// API CAlls
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

// AUTH
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCESS = 'AUTH_LOGIN_SUCESS';
