// TODOS
export const TODO_CREATE = 'TODO_CREATE';
export const TODOS_LOAD_INIT = 'TODOS_LOAD_INIT';
export const TODOS_LOAD_SUCCESS = 'TODOS_LOAD_SUCCESS';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_COMPLETE_COMPLETE = 'TODO_COMPLETE_COMPLETE';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_DELETE_OPTIMISTIC = 'TODO_DELETE_OPTIMISTIC';

// API CAlls
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

// USER
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_COMPLETE = 'USER_LOGOUT_COMPLETE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_SET_LOCAL_COMPLETE = 'USER_SET_LOCAL_COMPLETE';
export const USER_GET_LOCAL_COMPLETE = 'USER_GET_LOCAL_COMPLETE';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';

// HONEYS
export const HONEYS_LOAD_SUCCESS = 'HONEYS_LOAD_SUCCESS';

// DEWERS
export const DEWERS_LOAD_SUCCESS = 'DEWERS_LOAD_SUCCESS';
