// Courses
export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";

// TODOS
export const TODO_CREATE = 'TODO_CREATE';
export const TODOS_LOAD_SUCCESS = 'TODOS_LOAD_SUCCESS';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_DELETE_OPTIMISTIC = 'TODO_DELETE_OPTIMISTIC';

// API CAlls
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

// AUTH
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCESS = 'AUTH_LOGIN_SUCESS';
export const AUTH_SET_LOCAL_USER = 'AUTH_SET_LOCAL_USER';
// export const AUTH_GET_LOCAL_USER = 'AUTH_GET_LOCAL_USER';
export const AUTH_GET_LOCAL_USER_COMPLETE = 'AUTH_GET_LOCAL_USER_COMPLETE';

export const AUTH_SET_TOKEN_COMPLETE = 'AUTH_SET_TOKEN_COMPLETE';
export const AUTH_GET_TOKEN_COMPLETE = 'AUTH_GET_TOKEN_COMPLETE';
